from paddle_billing.PaddleStrEnum import PaddleStrEnum, PaddleStrEnumMeta


class ApiKeyPermission(PaddleStrEnum, metaclass=PaddleStrEnumMeta):
    AddressRead: "ApiKeyPermission" = "address.read"
    AddressWrite: "ApiKeyPermission" = "address.write"
    AdjustmentRead: "ApiKeyPermission" = "adjustment.read"
    AdjustmentWrite: "ApiKeyPermission" = "adjustment.write"
    BusinessRead: "ApiKeyPermission" = "business.read"
    BusinessWrite: "ApiKeyPermission" = "business.write"
    CustomerRead: "ApiKeyPermission" = "customer.read"
    CustomerWrite: "ApiKeyPermission" = "customer.write"
    CustomerAuthTokenWrite: "ApiKeyPermission" = "customer_auth_token.write"
    CustomerPortalSessionWrite: "ApiKeyPermission" = "customer_portal_session.write"
    DiscountRead: "ApiKeyPermission" = "discount.read"
    DiscountWrite: "ApiKeyPermission" = "discount.write"
    NotificationRead: "ApiKeyPermission" = "notification.read"
    NotificationWrite: "ApiKeyPermission" = "notification.write"
    NotificationSettingRead: "ApiKeyPermission" = "notification_setting.read"
    NotificationSettingWrite: "ApiKeyPermission" = "notification_setting.write"
    NotificationSimulationRead: "ApiKeyPermission" = "notification_simulation.read"
    NotificationSimulationWrite: "ApiKeyPermission" = "notification_simulation.write"
    PaymentMethodRead: "ApiKeyPermission" = "payment_method.read"
    PaymentMethodWrite: "ApiKeyPermission" = "payment_method.write"
    PriceRead: "ApiKeyPermission" = "price.read"
    PriceWrite: "ApiKeyPermission" = "price.write"
    ProductRead: "ApiKeyPermission" = "product.read"
    ProductWrite: "ApiKeyPermission" = "product.write"
    ReportRead: "ApiKeyPermission" = "report.read"
    ReportWrite: "ApiKeyPermission" = "report.write"
    SubscriptionRead: "ApiKeyPermission" = "subscription.read"
    SubscriptionWrite: "ApiKeyPermission" = "subscription.write"
    TransactionRead: "ApiKeyPermission" = "transaction.read"
    TransactionWrite: "ApiKeyPermission" = "transaction.write"
