version: 2
updates:
  - package-ecosystem: "pip"
    allow:
      - dependency-type: "all"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "08:00"
    reviewers:
      - "@PaddleHQ/developer-experience"
    labels:
      - "release:patch"
#    ignore:
#      - dependency-name: "setuptools"
#        versions: ["69.0.3"]
