from paddle_billing.PaddleStrEnum import PaddleStrEnum


class CurrencyCode(PaddleStrEnum):
    USD = 'USD'
    EUR = 'EUR'
    GBP = 'GBP'
    JPY = 'JPY'
    AUD = 'AUD'
    CAD = 'CAD'
    CHF = 'CHF'
    HKD = 'HKD'
    SGD = 'SGD'
    SEK = 'SEK'
    ARS = 'ARS'
    BRL = 'BRL'
    CNY = 'CNY'
    COP = 'COP'
    CZK = 'CZK'
    DKK = 'DKK'
    HUF = 'HUF'
    ILS = 'ILS'
    INR = 'INR'
    KRW = 'KRW'
    MXN = 'MXN'
    NOK = 'NOK'
    NZD = 'NZD'
    PLN = 'PLN'
    RUB = 'RUB'
    THB = 'THB'
    TRY = 'TRY'
    TWD = 'TWD'
    UAH = 'UAH'
    ZAR = 'ZAR'
