from paddle_billing.PaddleStrEnum import PaddleStrEnum, PaddleStrEnumMeta


class KoreaLocalPaymentMethodType(PaddleStrEnum, metaclass=PaddleStrEnumMeta):
    BC: "KoreaLocalPaymentMethodType" = "bc"
    Citi: "KoreaLocalPaymentMethodType" = "citi"
    Hana: "KoreaLocalPaymentMethodType" = "hana"
    Hyundai: "KoreaLocalPaymentMethodType" = "hyundai"
    Jeju: "KoreaLocalPaymentMethodType" = "jeju"
    Jeonbuk: "KoreaLocalPaymentMethodType" = "jeonbuk"
    KakaoBank: "KoreaLocalPaymentMethodType" = "kakaobank"
    KakaoPay: "KoreaLocalPaymentMethodType" = "kakaopay"
    KBank: "KoreaLocalPaymentMethodType" = "kbank"
    KDBBank: "KoreaLocalPaymentMethodType" = "kdbbank"
    Kookmin: "KoreaLocalPaymentMethodType" = "kookmin"
    Kwangju: "KoreaLocalPaymentMethodType" = "kwangju"
    Lotte: "KoreaLocalPaymentMethodType" = "lotte"
    MG: "KoreaLocalPaymentMethodType" = "mg"
    NaverPayCard: "KoreaLocalPaymentMethodType" = "naverpaycard"
    NaverPayPoint: "KoreaLocalPaymentMethodType" = "naverpaypoint"
    NH: "KoreaLocalPaymentMethodType" = "nh"
    PayCo: "KoreaLocalPaymentMethodType" = "payco"
    Post: "KoreaLocalPaymentMethodType" = "post"
    Samsung: "KoreaLocalPaymentMethodType" = "samsung"
    SamsungPay: "KoreaLocalPaymentMethodType" = "samsungpay"
    SavingsBank: "KoreaLocalPaymentMethodType" = "savingsbank"
    Shinhan: "KoreaLocalPaymentMethodType" = "shinhan"
    Shinhyup: "KoreaLocalPaymentMethodType" = "shinhyup"
    Suhyup: "KoreaLocalPaymentMethodType" = "suhyup"
    TossBank: "KoreaLocalPaymentMethodType" = "tossbank"
    Woori: "KoreaLocalPaymentMethodType" = "woori"
