name: Feature request
description: Suggest a new feature or idea for this SDK
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Please describe your feature request.
      description: A clear and concise description of what the problem is.
      placeholder: A clear and concise description of what the problem is.
  - type: textarea
    id: solution
    attributes:
      label: Describe your solution.
      description: A clear and concise description of what you want to happen.
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you have considered.
      description: A clear and concise description of any other options or features you have considered.
      placeholder: A clear and concise description of any other options or features you have considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request.
      placeholder: Add any other context about the feature request.