from json import loads
from pytest import mark
from urllib.parse import unquote

import respx
import httpx

from paddle_billing.Entities.Address import Address
from paddle_billing.Entities.Collections import AddressCollection
from paddle_billing.Entities.Shared import CountryCode, CustomData, Status

from paddle_billing.Resources.Addresses.Operations import CreateAddress, ListAddresses, UpdateAddress

from tests.Utils.ReadsFixture import ReadsFixtures


class TestAsyncAddressesClient:
    @mark.parametrize(
        "customer_id, operation, expected_request_body, expected_response_status, expected_response_body, expected_url",
        [
            (
                "ctm_01h844p3h41s12zs5mn4axja51",
                CreateAddress(CountryCode.AG),
                ReadsFixtures.read_raw_json_fixture("request/create_basic"),
                200,
                ReadsFixtures.read_raw_json_fixture("response/minimal_entity"),
                "/customers/ctm_01h844p3h41s12zs5mn4axja51/addresses",
            ),
            (
                "ctm_01h844p3h41s12zs5mn4axja51",
                CreateAddress(
                    country_code=CountryCode.US,
                    description="Head Office",
                    first_line="4050 Jefferson Plaza, 41st Floor",
                    second_line=None,
                    city="New York",
                    postal_code="10021",
                    region="NY",
                    custom_data=CustomData({"shippable": True}),
                ),
                ReadsFixtures.read_raw_json_fixture("request/create_full"),
                200,
                ReadsFixtures.read_raw_json_fixture("response/full_entity"),
                "/customers/ctm_01h844p3h41s12zs5mn4axja51/addresses",
            ),
        ],
        ids=[
            "Create address with basic data",
            "Create address with full data",
        ],
    )
    async def test_create_address_uses_expected_payload(
        self,
        async_test_client,
        customer_id,
        operation,
        expected_request_body,
        expected_response_status,
        expected_response_body,
        expected_url,
    ):
        full_url = f"{async_test_client.base_url}{expected_url}"

        with respx.mock() as mock:
            mock.post(full_url).respond(status_code=expected_response_status, text=expected_response_body)

            response = await async_test_client.client.addresses.create(customer_id, operation)

        request_json = async_test_client.client.payload
        response_json = async_test_client.client.addresses.response.json()

        assert isinstance(response, Address)
        assert async_test_client.client.status_code == expected_response_status
        assert (
            loads(request_json) == loads(expected_request_body)
        ), "The request JSON doesn't match the expected fixture JSON"
        assert response_json == loads(
            str(expected_response_body)
        ), "The response JSON doesn't match the expected fixture JSON"

    @mark.parametrize(
        "customer_id, address_id, expected_response_status, expected_response_body, expected_url",
        [
            (
                "ctm_01h844p3h41s12zs5mn4axja51",
                "add_01h848pep46enq8y372x7maj0p",
                200,
                ReadsFixtures.read_raw_json_fixture("response/full_entity"),
                "/customers/ctm_01h844p3h41s12zs5mn4axja51/addresses/add_01h848pep46enq8y372x7maj0p",
            )
        ],
        ids=["Get address"],
    )
    async def test_get_address_returns_expected_response(
        self,
        async_test_client,
        customer_id,
        address_id,
        expected_response_status,
        expected_response_body,
        expected_url,
    ):
        full_url = f"{async_test_client.base_url}{expected_url}"

        with respx.mock() as mock:
            mock.get(full_url).respond(status_code=expected_response_status, text=expected_response_body)

            response = await async_test_client.client.addresses.get(customer_id, address_id)

        response_json = async_test_client.client.addresses.response.json()

        assert isinstance(response, Address)
        assert async_test_client.client.status_code == expected_response_status
        assert response_json == loads(
            str(expected_response_body)
        ), "The response JSON generated by ResponseParser() doesn't match the expected fixture JSON"

    @mark.parametrize(
        "customer_id, expected_response_status, expected_response_body, expected_url",
        [
            (
                "ctm_01h844p3h41s12zs5mn4axja51",
                200,
                ReadsFixtures.read_raw_json_fixture("response/list_default"),
                "/customers/ctm_01h844p3h41s12zs5mn4axja51/addresses",
            )
        ],
        ids=["List addresses with default pagination"],
    )
    async def test_list_addresses_returns_expected_response(
        self,
        async_test_client,
        customer_id,
        expected_response_status,
        expected_response_body,
        expected_url,
    ):
        full_url = f"{async_test_client.base_url}{expected_url}"

        with respx.mock() as mock:
            mock.get(full_url).respond(status_code=expected_response_status, text=expected_response_body)

            response = await async_test_client.client.addresses.list(customer_id)

        assert isinstance(response, AddressCollection)
        assert async_test_client.client.status_code == expected_response_status

    async def test_archive_address_uses_expected_payload(self, async_test_client):
        customer_id = "ctm_01h844p3h41s12zs5mn4axja51"
        address_id = "add_01h848pep46enq8y372x7maj0p"
        full_url = f"{async_test_client.base_url}/customers/{customer_id}/addresses/{address_id}"
        response_body = ReadsFixtures.read_raw_json_fixture("response/full_entity")

        with respx.mock() as mock:
            mock.patch(full_url).respond(status_code=200, text=response_body)

            response = await async_test_client.client.addresses.archive(customer_id, address_id)

        request_json = async_test_client.client.payload
        assert isinstance(response, Address)
        assert loads(request_json)["status"] == Status.Archived.value

    async def test_async_iteration_over_collection(self, async_test_client):
        customer_id = "ctm_01h844p3h41s12zs5mn4axja51"
        full_url = f"{async_test_client.base_url}/customers/{customer_id}/addresses"
        response_body = ReadsFixtures.read_raw_json_fixture("response/list_default")

        with respx.mock() as mock:
            mock.get(full_url).respond(status_code=200, text=response_body)

            collection = await async_test_client.client.addresses.list(customer_id)

        items = []
        async for item in collection:
            items.append(item)
            assert isinstance(item, Address)

        assert len(items) == len(collection.items)
