from paddle_billing.PaddleStrEnum import PaddleStrEnum, PaddleStrEnumMeta


class CurrencyCode(PaddleStrEnum, metaclass=PaddleStrEnumMeta):
    USD: "CurrencyCode" = "USD"
    EUR: "CurrencyCode" = "EUR"
    GBP: "CurrencyCode" = "GBP"
    JPY: "CurrencyCode" = "JPY"
    AUD: "CurrencyCode" = "AUD"
    CAD: "CurrencyCode" = "CAD"
    CHF: "CurrencyCode" = "CHF"
    HKD: "CurrencyCode" = "HKD"
    SGD: "CurrencyCode" = "SGD"
    SEK: "CurrencyCode" = "SEK"
    ARS: "CurrencyCode" = "ARS"
    BRL: "CurrencyCode" = "BRL"
    CNY: "CurrencyCode" = "CNY"
    COP: "CurrencyCode" = "COP"
    CZK: "CurrencyCode" = "CZK"
    DKK: "CurrencyCode" = "DKK"
    HUF: "CurrencyCode" = "HUF"
    ILS: "CurrencyCode" = "ILS"
    INR: "CurrencyCode" = "INR"
    KRW: "CurrencyCode" = "KRW"
    MXN: "CurrencyCode" = "MXN"
    NOK: "CurrencyCode" = "NOK"
    NZD: "CurrencyCode" = "NZD"
    PLN: "CurrencyCode" = "PLN"
    RUB: "CurrencyCode" = "RUB"
    THB: "CurrencyCode" = "THB"
    TRY: "CurrencyCode" = "TRY"
    TWD: "CurrencyCode" = "TWD"
    UAH: "CurrencyCode" = "UAH"
    ZAR: "CurrencyCode" = "ZAR"
