name: Run Tests

on:
  #  release:
  #    types: [created]
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Package stability ${{ matrix.stability }}"
    runs-on:  ubuntu-latest
    environment: dev
    permissions:
      contents: read

    strategy:
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          allow-prereleases: ${{ matrix.python-version == '3.13' }}
          python-version:    ${{ matrix.python-version }}

      - name: Install pip dependencies
        run:  |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"

      - name: Run Python tests
        run:  pytest
